### ISSUE TITLE
请问这个错误如何解决？

### ISSUE THREAD

**Issue by KawaUso-Jyou** [Cyenoch/zjy2.icve#2]
`获取课程列表...
Traceback (most recent call last):
  File "C:\Users\KawaUso\Downloads\1.py", line 632, in <module>
    cliMain()
  File "C:\Users\KawaUso\Downloads\1.py", line 626, in cliMain
    courseList = getCourseList()  #
  File "C:\Users\KawaUso\Downloads\1.py", line 125, in getCourseList
    return sess.get(
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\KawaUso\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`

**Comment by Cyenoch** [comment]
你开梯子了？

**Comment by KawaUso-Jyou** [comment]
啊这，原来挂着梯子不行呀。关了梯子已经可以了，谢谢🙏。

Cyenoch ***@***.***>于2021年4月10日 周六17:03写道：
